=== hippocampusSwapper/NodeChain/Connector/bch/rpcschemas/config.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "",
    "description": "",
    "type": "object",
    "properties": {
        "bitcoincoreProtocol" : {
            "type" : "string"
        },
        "bitcoincoreHost": {
            "type": "string"
        },
        "bitcoincorePort": {
            "type": "integer"
        },
        "bitcoincoreUser":{
          "type": "string"
        },
        "bitcoincorePassword": {
            "type": "string"
        },
        "electrumCashProtocol": {
            "type": "string"
        },
        "electrumCashHost": {
            "type": "string"
        },
        "electrumCashPort": {
            "type": "integer"
        },
        "electrumCashUser": {
            "type": "string"
        },
        "electrumCashPassword": {
            "type": "string"
        }
    },
    "required": [
        "bitcoincoreProtocol",
        "bitcoincoreHost",
        "bitcoincorePort",
        "bitcoincoreUser",
        "bitcoincorePassword",
        "electrumCashProtocol",
        "electrumCashHost",
        "electrumCashPort",
        "electrumCashUser",
        "electrumCashPassword"
    ]
}

=== hippocampusSwapper/NodeChain/Connector/bch/defaultConf.json
{
  "bitcoincoreProtocol": "http",
  "bitcoincoreHost": "bitcoincore",
  "bitcoincorePort": 8332,
  "bitcoincoreUser": "swapper",
  "bitcoincorePassword": "swapper",
  "electrumCashProtocol": "http",
  "electrumCashHost": "electrum",
  "electrumCashPort": 30000,
  "electrumCashUser": "swapper",
  "electrumCashPassword": "swapper"
}
