=== hippocampusSwapper/NodeChain/Connector/btc/rpcschemas/config.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "",
    "description": "",
    "type": "object",
    "properties": {
        "bitcoincoreProtocol" : {
            "type" : "string"
        },
        "bitcoincoreHost": {
            "type": "string"
        },
        "bitcoincorePort": {
            "type": "integer"
        },
        "bitcoincoreUser":{
          "type": "string"
        },
        "bitcoincorePassword": {
            "type": "string"
        },
        "bitcoincoreZmqProtocol": {
            "type": "string"
        },
        "bitcoincoreCallbackProtocol": {
            "type": "string",
            "enum": [
                "http",
                "https"
            ]
        },
        "bitcoincoreCallbackHost": {
            "type": "string"
        },
        "bitcoincoreZmqPort": {
            "type": "integer"
        },
        "electrumProtocol": {
            "type": "string"
        },
        "electrumHost": {
            "type": "string"
        },
        "electrumPort": {
            "type": "integer"
        },
        "electrumUser": {
            "type": "string"
        },
        "electrumPassword": {
            "type": "string"
        }
    },
    "required": [
        "bitcoincoreProtocol",
        "bitcoincoreHost",
        "bitcoincorePort",
        "bitcoincoreUser",
        "bitcoincorePassword",
        "bitcoincoreZmqProtocol",
        "bitcoincoreZmqPort",
        "electrumProtocol",
        "electrumHost",
        "electrumPort",
        "electrumUser",
        "electrumPassword"
    ]
}

=== hippocampusSwapper/NodeChain/Connector/btc/defaultConf.json
{
  "bitcoincoreProtocol": "http",
  "bitcoincoreHost": "bitcoincore",
  "bitcoincorePort": 8332,
  "bitcoincoreUser": "swapper",
  "bitcoincorePassword": "swapper",
  "bitcoincoreZmqProtocol": "tcp",
  "bitcoincoreZmqPort": 28332,
  "electrumProtocol": "http",
  "electrumHost": "electrum",
  "electrumPort": 30000,
  "electrumUser": "swapper",
  "electrumPassword": "swapper"
}
